# Generated by Django 5.1.1 on 2024-09-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_socialmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
