# Generated by Django 5.1.1 on 2024-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_socialmedia_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='comment',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
